version: '3.8'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME}
      - SONAR_JDBC_PASSWORD=${SONAR_JDBC_PASSWORD}
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data

volumes:
  sonarqube_db_data:
