services:
  - type: web
    name: sonarqube
    env: docker
    repo: https://github.com/keypuncheralwin/sonarcube-test
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "java -jar /opt/sonarqube/lib/sonar-application-${SONARQUBE_VERSION}.jar"
    envVars:
      - key: SONAR_JDBC_URL
        value: jdbc:postgresql://sonarqube-db:5432/sonarqube
      - key: SONAR_JDBC_USERNAME
        value: ${SONAR_JDBC_USERNAME}
      - key: SONAR_JDBC_PASSWORD
        value: ${SONAR_JDBC_PASSWORD}
    ports:
      - 9000

  - type: web
    name: sonarqube-db
    env: docker
    repo: https://github.com/keypuncheralwin/sonarcube-test
    branch: main
    dockerfilePath: Dockerfile.db
    buildCommand: ""
    startCommand: "docker-entrypoint.sh postgres"
    envVars:
      - key: POSTGRES_USER
        value: ${POSTGRES_USER}
      - key: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD}
      - key: POSTGRES_DB
        value: ${POSTGRES_DB}
